name = "example"
version = "0.1.0"

on_finish = ["notify_send"]

[[plugins]]
name = "notify_send"
config = { app_name = "XTomate" }

[tasks.notify_send]
run = false
plugin = "notify_send"
config = { message = "Workflow finished" }

[tasks.prepdir]
command = """
mkdir testdir
cd testdir
touch hello.py
"""

[tasks.createprogram]
command = '''
echo "print('hello world')" > testdir/hello.py
'''
dependencies = [{"prepdir" = "success"}]

[tasks.writefile]
command = '''
echo "$WORLD $HELLO" > testdir/hello.txt
'''
dependencies = [{"prepdir" = "success"}]
env = {HELLO = "world", WORLD = "hello"}

[tasks.runprogram]
command = "python testdir/hello.py && cat testdir/hello.txt"
dependencies = [{"createprogram" = "success"}, {"writefile" = "success"}]
